## Part 1 - Model definition
---

In [2]:
import torch

In [4]:
from torch.autograd import Variable

In [5]:
x_data = Variable(torch.Tensor([[1.0],[2.0],[3.0]]))
y_data = Variable(torch.Tensor([[2.0],[4.0],[6.0]]))
print(x_data)
print(y_data)

tensor([[1.],
        [2.],
        [3.]])
tensor([[2.],
        [4.],
        [6.]])


In [7]:
class LinearRegressionModel(torch.nn.Module):

    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.linear = torch.nn.Linear(1, 1) # one input -> one output
    
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred



In [8]:
linear_model = LinearRegressionModel()

## Part 2 - Loss function and Optimiser
---

Source: https://github.com/jcjohnson/pytorch-examples

In [11]:
# loss function - Mean Square Error
criterion = torch.nn.MSELoss(size_average=False)

In [17]:
# optimiser - Stochastic Gradient Descent
learning_rate = 0.01
optimiser = torch.optim.SGD(linear_model.parameters(), lr=learning_rate)

## Part 3 - Training loop

In [27]:
eval_var = Variable(torch.Tensor([[4.0]]))
print("prediction (before training: ", 4, linear_model.forward(eval_var).data[0][0])

prediction (before training:  4 tensor(-3.2897)


In [31]:
w_list = []
l_list = []

for epoch in range(500):
    # forward pass
    y_pred = linear_model(x_data)
    print(y_pred)

    # compute loss function
    loss = criterion(y_pred, y_data)
    print(epoch, loss.data)

    # backpropagation and optimiser
    optimiser.zero_grad()
    loss.backward()
    optimiser.step()

)
tensor([[2.0751],
        [4.0161],
        [5.9571]], grad_fn=<AddmmBackward>)
298 tensor(0.0077)
tensor([[2.0746],
        [4.0160],
        [5.9574]], grad_fn=<AddmmBackward>)
299 tensor(0.0076)
tensor([[2.0740],
        [4.0159],
        [5.9577]], grad_fn=<AddmmBackward>)
300 tensor(0.0075)
tensor([[2.0735],
        [4.0158],
        [5.9581]], grad_fn=<AddmmBackward>)
301 tensor(0.0074)
tensor([[2.0730],
        [4.0157],
        [5.9584]], grad_fn=<AddmmBackward>)
302 tensor(0.0073)
tensor([[2.0724],
        [4.0155],
        [5.9587]], grad_fn=<AddmmBackward>)
303 tensor(0.0072)
tensor([[2.0719],
        [4.0154],
        [5.9590]], grad_fn=<AddmmBackward>)
304 tensor(0.0071)
tensor([[2.0714],
        [4.0153],
        [5.9592]], grad_fn=<AddmmBackward>)
305 tensor(0.0070)
tensor([[2.0709],
        [4.0152],
        [5.9595]], grad_fn=<AddmmBackward>)
306 tensor(0.0069)
tensor([[2.0704],
        [4.0151],
        [5.9598]], grad_fn=<AddmmBackward>)
307 tensor(0.0068)
tensor([

In [37]:
print("prediction (after training: ", 4, round(linear_model.forward(eval_var).data.item(), 2))

prediction (after training:  4 7.98


https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py