In [5]:
import torch
from torch.autograd import Variable
import torch.nn.functional as F

In [4]:
x_data = Variable(torch.Tensor([[1.0], [2.0], [3.0], [4.0]]))
y_data = Variable(torch.Tensor([[0.], [0.], [1.], [1.]]))
print(x_data)
print(y_data)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[0.],
        [0.],
        [1.],
        [1.]])


In [6]:
class LogisticRegressionModel(torch.nn.Module):
    
    def __init__(self):
        super(LogisticRegressionModel, self).__init__()
        self.linear = torch.nn.Linear(1, 1)

    def forward(self, x):
        y_pred = F.sigmoid(self.linear(x))
        return y_pred
    

In [17]:
logistic_model = LogisticRegressionModel()

---

In [18]:
criterion = torch.nn.BCELoss(size_average=True)

In [19]:
learning_rate = 0.01
optimiser = torch.optim.SGD(logistic_model.parameters(), lr=learning_rate)

---

In [28]:
for epoch in range(500):
    y_pred = logistic_model.forward(x_data)
    loss = criterion(y_pred, y_data)
    print(epoch, round(loss.data.item(), 2))
    optimiser.zero_grad()
    loss.backward()
    optimiser.step()

0 0.67
1 0.67
2 0.67
3 0.67
4 0.67
5 0.67
6 0.67
7 0.67
8 0.67
9 0.67
10 0.67
11 0.67
12 0.67
13 0.67
14 0.67
15 0.67
16 0.67
17 0.67
18 0.67
19 0.67
20 0.67
21 0.67
22 0.67
23 0.67
24 0.67
25 0.67
26 0.67
27 0.67
28 0.67
29 0.67
30 0.67
31 0.67
32 0.66
33 0.66
34 0.66
35 0.66
36 0.66
37 0.66
38 0.66
39 0.66
40 0.66
41 0.66
42 0.66
43 0.66
44 0.66
45 0.66
46 0.66
47 0.66
48 0.66
49 0.66
50 0.66
51 0.66
52 0.66
53 0.66
54 0.66
55 0.66
56 0.66
57 0.66
58 0.66
59 0.66
60 0.66
61 0.66
62 0.66
63 0.66
64 0.66
65 0.66
66 0.66
67 0.66
68 0.65
69 0.65
70 0.65
71 0.65
72 0.65
73 0.65
74 0.65
75 0.65
76 0.65
77 0.65
78 0.65
79 0.65
80 0.65
81 0.65
82 0.65
83 0.65
84 0.65
85 0.65
86 0.65
87 0.65
88 0.65
89 0.65
90 0.65
91 0.65
92 0.65
93 0.65
94 0.65
95 0.65
96 0.65
97 0.65
98 0.65
99 0.65
100 0.65
101 0.65
102 0.65
103 0.65
104 0.65
105 0.64
106 0.64
107 0.64
108 0.64
109 0.64
110 0.64
111 0.64
112 0.64
113 0.64
114 0.64
115 0.64
116 0.64
117 0.64
118 0.64
119 0.64
120 0.64
121 0.64
122 0.64
123

In [26]:
test_data_1 = Variable(torch.Tensor([[1.0]]))
test_data_2 = Variable(torch.Tensor([[7.0]]))

In [29]:
for test_data in (test_data_1, test_data_2):
    prediction = round(logistic_model.forward(test_data).data.item(), 2)
    prediction_class = prediction > 0.5
    print(test_data, prediction, prediction_class)





tensor([[1.]]) 0.49 False
tensor([[7.]]) 0.92 True
